-- AlterTable
ALTER TABLE "Apicultores" ADD COLUMN     "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
ADD COLUMN     "status" BOOLEAN,
ADD COLUMN     "updated_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6);
